[package]
name = "es_runtime"
version = "0.0.2"
authors = ["Andries Hiemstra"]
edition = "2018"
description = "es_runtime crate which is an api around the spidermonkey script engine"
homepage = "https://gitlab.com/drfos/es_runtime"
keywords = ["script", "javascript", "es6", "ecmascript", "spidermonkey"]
repository = "https://gitlab.com/drfos/es_runtime.git"
license = "GPL-3.0"
license-file = "LICENSE"
documentation = "https://gitlab.com/drfos/es_runtime"
readme = "README.md"
categories = ["development-tools"]

[dependencies]
mozjs = "0.10.1"
libc = "0.2.68"
lazy_static = "1.4.0"
log = "0.4.8"
simple_logger = "1.3.0"
thread-id = "3.3.0"
num_cpus = "1.0"
uuid = {version = "0.8.1", features =["v4"]}
rayon = "1.3.0"
