name: Rust

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Prepare
      run: |
        sudo apt update
        sudo apt install gcc-7 llvm autoconf2.13 automake clang python -y
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
